# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FarePare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FarePare
  pod 'UberRides', :git => 'https://github.com/uber/rides-ios-sdk.git', :branch => 'swift-3-dev'
end
